"""Add Group and Site tables

Revision ID: 77d4ae67dc40
Revises:
Create Date: 2024-05-31 11:48:59.708961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d4ae67dc40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('type', sa.Enum('GROUP1', 'GROUP2', 'GROUP3', name='group_type'), nullable=True),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['groups.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'sites',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('installation_date', sa.Date(), nullable=False),
        sa.Column('max_power_megawatt', sa.Float(), nullable=False),
        sa.Column('min_power_megawatt', sa.Float(), nullable=False),
        sa.Column('useful_energy_at_1_megawatt', sa.Float(), nullable=True),
        sa.Column('efficiency', sa.Float(), nullable=True),
        sa.Column('country', sa.Enum('FR', 'IT', name='country_enum'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table(
        'site_group_association',
        sa.Column('site_id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
        sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
        sa.PrimaryKeyConstraint('site_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_group_association')
    op.drop_table('sites')
    op.drop_table('groups')
    # ### end Alembic commands ###
